apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vdt-be.fullname" . }}
  labels:
    {{- include "vdt-be.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vdt-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vdt-be.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vdt-be.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.env.values }}
          {{- range $v := $.Values.env.values }}
            - name: {{ $v.name }}
              value: {{ $v.value | quote}}
          {{- end }}
          {{- end }}
          {{- if .Values.env.configmaps }}
          {{- range $v := $.Values.env.configmaps }}
            - name: {{ $v.name }}
              valueFrom: 
                configMapKeyRef:
                  name: {{ $v.configMapName }}
                  key:  {{ $v.configMapKey }}
          {{- end }}
          {{- end }}
            {{- if .Values.env.secrets }}
            {{- range $v := $.Values.env.secrets }}
            - name: {{ $v.name }}
              valueFrom: 
                secretKeyRef:
                  name: {{ $v.secretName }}
                  key:  {{ $v.secretKey }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
