name: VDT2024 CI
run-name: "Publish docker image commit sha ${{ inputs.SHA || github.sha }} by @${{ github.actor }}"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]
env:
  DB_USER: test
  DB_PASSWORD: testuser4321
  DB_NAME: test
  DB_PORT: 3306
  DB_HOST: 127.0.0.1
  COR_ORIGIN: '*'
  API_PATH: /api/v1
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' &&  ${{ github.event.pull_request.merged }}  # run this job only for the main branch
    environment: ci
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/backend
          tag: |
            type=ref,event=branch
            type=ref,event=pr
      - 
        name: Set short sha
        id: sha_short
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "sha_short=$calculatedSha" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ steps.meta.outputs.tags }}-${{ steps.sha_short.outputs.sha_short }}"
          labels: ${{ steps.meta.outputs.labels }}