name: Build and Publish docker image
run-name: "Publish docker image commit sha ${{ inputs.SHA || github.sha }} by @${{ github.actor }}"

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  push:
    tags:
      - 'v*'
    # branches:
    #   - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    outputs: 
      tag: "${{ steps.meta.outputs.tags }}"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/backend
          tag: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,event=tag,pattern={{raw}}
      
      - 
        name: Set short sha
        id: sha_short
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "sha_short=$calculatedSha" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # -${{ steps.sha_short.outputs.sha_short }}
      -
        name: Build and push
        id: capture-tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm/v8
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-cache:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-cache:latest,mode=max
  modify_image_tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Changing the deployment of git repo
        with:
          repository: DoTruong1/vdt-backend-config-repo
          token: ${{ secrets.GITOPS_TOKEN }}
          ref: HEAD
      - name: modify the image
        run: |
          git config user.email ${{ secrets.email }}
          git config user.name ${{ secrets.name }}
          echo “Working Directory: $(pwd)”
        
          # Navigate to the specific Helm chart directory
          cd helm-chart-dir
          
          # Print values.yaml for debugging before changes
          echo “Before modification:”
          cat values.yaml
          
          sed -i '/^image:/,/^ tag:/{s/^ tag: .*/ tag: "'$TAG'"/}' values.yaml
          
          # Print values.yaml for debugging after changes
          echo “After modification:”
          cat values.yaml
          
          git add values.yaml
          git commit -m “Update image tag by Github Actions Job change manifest: ${{ github.run_number }}”
          git push origin dev
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GITOPS_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}
          TAG: ${{ needs.build.outputs.tag }}
         
