name: Build and Publish docker image
run-name: "Publish docker image commit sha ${{ inputs.SHA || github.sha }} by @${{ github.actor }}"

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  push:
    tags:
      - 'v*'
    # branches:
    #   - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    outputs: 
      tag: ${{ steps.tag.outputs.out }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/backend
          tag: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,event=tag,pattern={{raw}}
    
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # -${{ steps.sha_short.outputs.sha_short }}
      -
        name: Build and push
        id: capture-tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm/v8
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-cache:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-cache:latest,mode=max
      
      - uses: cloudposse/github-action-secret-outputs@main
        id: tag
        with:
            ## PASSWORD is a gpg passphrase stored in Github Secrets.
          secret: ${{ secrets.GITOPS_TOKEN }}
          op: encode
          in: ${{ steps.meta.outputs.tag }}
          
  # modify_image_tag:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: ci
    
  #   steps:
  #     - uses: cloudposse/github-action-secret-outputs@main
  #       id: tag
  #       with:
  #           ## PASSWORD is a gpg passphrase stored in Github Secrets.          
  #           secret: ${{ secrets.GITOPS_TOKEN }}
  #           op: decode
  #           in: ${{ needs.build.outputs.tag }}
  #     - env:
  #         GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  #         GIT_PASSWORD: ${{ secrets.GITOPS_TOKEN }}
  #         RUN_NUMBER: ${{ github.run_number }}
  #         TAG: ${{ steps.tag.outputs.out }}
  #       run: echo "$TAG"
      - uses: actions/checkout@v3
        name: Changing the deployment of git repo
        with:
          repository: DoTruong1/vdt-backend-config-repo
          token: ${{ secrets.GITOPS_TOKEN }}
          ref: main
          path: ./config
      - name: modify the image
        run: |
          echo $TAG
          cd ./config
          git config user.email "aa@gmail.com"
          git config user.name ${{ secrets.GIT_USERNAME }}
          echo “Working Directory: $(pwd)”
        
          # Navigate to the specific Helm chart directory
          
          # Print values.yaml for debugging before changes
          echo “Before modification:”
          cat values.yaml
          
          sed -i '/^image:/,/^ tag:/{s/^ tag: .*/ tag: "'${{ steps.meta.outputs.tags }}'"/}' values.yaml
          
          # Print values.yaml for debugging after changes
          echo “After modification:”
          cat values.yaml
          
          git add values.yaml
          git commit -m “Update image tag by Github Actions Job change manifest: ${{ github.run_number }}”
          git push origin main
      
         
