name: Build and Publish docker image
run-name: "Publish docker image commit sha ${{ inputs.SHA || github.sha }} by @${{ github.actor }}"

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  push:
    tags:
      - 'v*'
    # branches:
    #   - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/backend
          tag: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      
      - 
        name: Set short sha
        id: sha_short
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "sha_short=$calculatedSha" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # -${{ steps.sha_short.outputs.sha_short }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          # push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ steps.meta.outputs.tags }}"
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-cache:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-cache:latest,mode=max